[project]
name = "auai2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dnd-auction-game>=0.3.1",
    "uvicorn>=0.32.1",
]
